package com.example.tekhstor.enums;

public enum State {

    FREE,
    FOLDER_SHOW, FOLDER_ADD, FOLDER_DELETE, FOLDER_MAIN, FOLDER_ADD_WAIT_NAME, FOLDER_DELETE_WAIT_NAME,
    CONTACT_SHOW, CONTACT_ADD, CONTACT_DELETE, CONTACT_MAIN, CONTACT_ADD_WAIT_FOLDER, CONTACT_ADD_WAIT_USER_NAME,CONTACT_DELETE_WAIT_FOLDER, CONTACT_DELETE_WAIT_USER_NAME,

    FOLDER_MESSAGE_WAIT_FOLDER, FOLDER_MESSAGE_WAIT_MESSAGE
}
